name: New Mod Request
description: Suggest a new mod to port to MineClone2
title: "[Mod]: "
labels: ["bug"]
body:
  - type: textarea
    id: mod-description
    attributes:
      label: Describe the mod
      description: What is the purpose of the mod?
    validations:
      required: true
  - type: checkboxes
    id: category
    attributes:
      label: Which category describe the mod well?
      description: You may select more than one.
      options:
        - label: World Gen
        - label: Technology
        - label: Magic
        - label: Storage
        - label: API and Library
        - label: Adventure and RPG
        - label: Map and Information
        - label: Cosmetic
        - label: Miscellanous
        - label: Armor, Tools, Weapons
        - label: Server Utility
        - label: Food
        - label: Redstone
  - type: input
    id: link
    attributes:
      label: Link to original mod
      description: Which is the link of the website of the mod?
      placeholder: ex. https://www.curseforge.com/minecraft/mc-mods/dummy-mod
    validations:
      required: true
  - type: dropdown
    id: code
    attributes:
      label: Source Code
      description: Is the code availlable and if so, which is his licence?
      options:
        - No (unavaillable)
        - Yes (non-free)
        - Yes (MIT)
        - Yes (GPL)
    validations:
      required: true
  - type: dropdown
    id: version
    attributes:
      label: Minecraft Version
      description: Which Minecraft version is the mod for?
      options:
        - 1.17
        - 1.16
        - 1.15
        - 1.14
        - 1.13
        - 1.12
        - 1.11
        - 1.10
        - 1.9
        - 1.8
        - 1.7
    validations:
      required: true
  - type: dropdown
    id: engine
    attributes:
      label: Engine
      description: Do the mod use Forge or Fabric?
      options:
        - Forge
        - Fabric
    validations:
      required: true
