name: New Mod Request
description: Suggest a new mod to port to MineClone2
title: "[Mod]: "
labels: ["New Mod"]
body:
  - type: textarea
    id: mod-description
    attributes:
      label: Describe the mod
      description: What is the purpose of the mod?
    validations:
      required: true
  - type: input
    id: link
    attributes:
      label: Link to original mod
      description: Which is the link of the website of the mod?
      placeholder: ex. https://www.curseforge.com/minecraft/mc-mods/dummy-mod
    validations:
      required: true
  - type: dropdown
    id: code
    attributes:
      label: Source Code
      description: Is the code availlable and if so, which is his licence?
      options:
        - No (unavaillable)
        - Yes (non-free)
        - Yes (MIT)
        - Yes (GPL)
        - Yes (LGPL)
        - Yes (MMPL)
        - Yes (EPL)
        - Yes (Apache)
    validations:
      required: true
  - type: dropdown
    id: version
    attributes:
      label: Minecraft Version
      description: Which Minecraft version is the mod for?
      options:
        - 1.18
        - 1.17
        - 1.16
        - 1.15
        - 1.14
        - 1.13
        - 1.12
        - 1.11
        - 1.10
        - 1.9
        - 1.8
        - 1.7
    validations:
      required: true
  - type: dropdown
    id: engine
    attributes:
      label: Engine
      description: Do the mod use Forge or Fabric?
      options:
        - Forge
        - Fabric
    validations:
      required: true
