name: New Mod Request
description: Suggest a new mod to port to MineClone2
title: "[Mod]: "
labels: ["bug"]
assignees:
  - octocat
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this bug report!
  - type: input
    id: link
    attributes:
      label: Link to original mod
      description: Which is the link of the website of the mod?
      placeholder: ex. https://www.curseforge.com/minecraft/mc-mods/dummy-mod
    validations:
      required: true
  - type: textarea
    id: what-happened
    attributes:
      label: What happened?
      description: Also tell us, what did you expect to happen?
      placeholder: Tell us what you see!
      value: "A bug happened!"
    validations:
      required: true
  - type: dropdown
    id: version
    attributes:
      label: Minecraft Version
      description: What version Minecraft is the mod for?
      options:
        - 1.17
        - 1.12
        - 1.8
    validations:
      required: true
  - type: dropdown
    id: engine
    attributes:
      label: Engine
      description: Do the mod use Forge or Fabric?
      options:
        - Forge
        - Fabric
    validations:
      required: true
