name: Add new mods to project

on:
  issues:
    types:
      - labeled

jobs:
  add-to-project:
    name: Add new mods to project
    runs-on: ubuntu-latest
    steps:
      - uses: actions/add-to-project@main
        with:
          project-url: https://github.com/orgs/mineclone2-mods/projects/2
          github-token: ${{ secrets.ADD_TO_PROJECT_PAT }}
          labeled: ✅ Approved
          label-operator: OR
